get http://localhost:4000/user-api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFyanVuIiwiaWF0IjoxNzIwODY3NDYyLCJleHAiOjE3MjA4NzEwNjJ9.8AH1Kut5sDspMKpF85ZTKyVt-Hm8iiWm7hQ9qrfAkWI
### 

get http://localhost:4000/user-api/users/arjun
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFyanVuIiwiaWF0IjoxNzIwODY3NDYyLCJleHAiOjE3MjA4NzEwNjJ9.8AH1Kut5sDspMKpF85ZTKyVt-Hm8iiWm7hQ9qrfAkWI
###

post http://localhost:4000/user-api/user
Content-Type: application/json

{
    "name":"Arjun",
    "email":"arjun@gmail.com",
    "password":"arjun",
    "username":"arjun"
}
###

post http://localhost:4000/user-api/login
Content-Type: application/json

{
    "username":"arjun",
    "password":"arjun"
}
###

put http://localhost:4000/user-api/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFyanVuIiwiaWF0IjoxNzIwODY3NDYyLCJleHAiOjE3MjA4NzEwNjJ9.8AH1Kut5sDspMKpF85ZTKyVt-Hm8iiWm7hQ9qrfAkWI

{
    "name":"Arjun reddy",
    "email":"arjunreddy@gmail.com",
    "password":"arjun",
    "username":"arjun"
}
###

delete http://localhost:4000/user-api/user/arjun
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFyanVuIiwiaWF0IjoxNzIwODY3NDYyLCJleHAiOjE3MjA4NzEwNjJ9.8AH1Kut5sDspMKpF85ZTKyVt-Hm8iiWm7hQ9qrfAkWI
###