get http://localhost:4000/user-api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFyanVuIiwiaWF0IjoxNzIxOTcwMDk1LCJleHAiOjE3MjE5NzM2OTV9.8t1iuDD2xmF4bUtPObohL7LYnwfdhGqJLaMOGOq-ngQ
### 

get http://localhost:4000/user-api/users/arjun
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFyanVuIiwiaWF0IjoxNzIxOTcwMDk1LCJleHAiOjE3MjE5NzM2OTV9.8t1iuDD2xmF4bUtPObohL7LYnwfdhGqJLaMOGOq-ngQ
###

post http://localhost:4000/user-api/user
Content-Type: application/json

{
    "name":"Arjun",
    "email":"arjun@gmail.com",
    "password":"arjun",
    "username":"arjun",
    "products":[]
}
###

post http://localhost:4000/user-api/login
Content-Type: application/json

{
    "username":"arjun",
    "password":"arjun"
}
###

put http://localhost:4000/user-api/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFyanVuIiwiaWF0IjoxNzIxOTcwMDk1LCJleHAiOjE3MjE5NzM2OTV9.8t1iuDD2xmF4bUtPObohL7LYnwfdhGqJLaMOGOq-ngQ

{
    "name":"Arjun reddy",
    "email":"arjunreddy@gmail.com",
    "password":"arjun",
    "username":"arjun"
}
###

delete http://localhost:4000/user-api/user/arjun
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFyanVuIiwiaWF0IjoxNzIxOTcwMDk1LCJleHAiOjE3MjE5NzM2OTV9.8t1iuDD2xmF4bUtPObohL7LYnwfdhGqJLaMOGOq-ngQ
###

get http://localhost:4000/product-api/products
###
get http://localhost:4000/product-api/products/12
###

put http://localhost:4000/user-api/add-to-cart/arjun
Content-Type: application/json

{
    "products":{
        "id":1,
       "title":"Essence Mascara Lash Princess",
       "description":"The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.",
       "category":"beauty",
       "price":9.99
    }
}
###